# change the followings to match your Github username and repo name
baseurl: "/tjs8" # the name of your github repo
url: "https://tallinnjs.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "TallinnJS 8"
description: TallinnJS is a group of developers passionate about JavaScript and eager to gather together to share best practices and learn from each-other while having great time together.

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Satoshi Nakamoto
author-bio: Creator of Bitcoin  # change to false to hide
author-image: 279.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Bitcoin
  permalink: bitcoin
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: https://twitter.com/
facebook: https://facebook.com/
instagram: https://instagram.com/
github: https://github.com/
linkedin: https://linkedin.com/
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag